In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('/Users/macbook/Projects/Python_code/Data preparation/Data_prep.csv', low_memory = False)

In [37]:
data

,communityname,state,countyCode,communityCode,fold,population,householdsize,racepctblack,racePctWhite,racePctAsian,...,burglaries,burglPerPop,larcenies,larcPerPop,autoTheft,autoTheftPerPop,arsons,arsonsPerPop,ViolentCrimesPerPop,nonViolPerPop
0,BerkeleyHeightstownship,NJ,39,5320,1,11980,3.10,1.37,91.78,6.50,...,14,114.85,138,1132.08,16,131.26,2,16.41,41.02,1394.59
1,Marpletownship,PA,45,47616,1,23123,2.82,0.80,95.57,3.44,...,57,242.37,376,1598.78,26,110.55,1,4.25,127.56,1955.95
2,Tigardcity,OR,?,?,1,29344,2.43,0.74,94.33,3.43,...,274,758.14,1797,4972.19,136,376.3,22,60.87,218.59,6167.51
3,Gloversvillecity,NY,35,29443,1,16656,2.40,1.70,97.35,0.50,...,225,1301.78,716,4142.56,47,271.93,?,?,306.64,?
4,Bemidjicity,MN,7,5068,1,11245,2.76,0.53,89.16,1.17,...,91,728.93,1060,8490.87,91,728.93,5,40.05,?,9988.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2210,Mercedcity,CA,?,?,10,56216,3.07,6.87,61.68,15.23,...,1376,2268.72,2563,4225.82,489,806.25,34,56.06,545.75,7356.84
2211,Pinevillecity,LA,?,?,10,12251,2.68,21.18,76.65,1.52,...,104,860.43,574,4748.9,24,198.56,2,16.55,124.1,5824.44
2212,Yucaipacity,CA,?,?,10,32824,2.46,0.52,92.62,0.98,...,628,1709.26,895,2435.97,179,487.19,8,21.77,353.83,4654.2
2213,Beevillecity,TX,?,?,10,13547,2.89,3.37,69.91,0.90,...,192,1508.01,474,3722.9,13,102.1,1,7.85,691.17,5340.87
2214,WestSacramentocity,CA,?,?,10,28898,2.61,2.39,71.27,9.09,...,791,2614.53,1458,4819.2,405,1338.67,20,66.11,918.89,8838.5

In [5]:
data.replace('?', np.nan)

,communityname,state,countyCode,communityCode,fold,population,householdsize,racepctblack,racePctWhite,racePctAsian,...,burglaries,burglPerPop,larcenies,larcPerPop,autoTheft,autoTheftPerPop,arsons,arsonsPerPop,ViolentCrimesPerPop,nonViolPerPop
0,BerkeleyHeightstownship,NJ,39,5320,1,11980,3.10,1.37,91.78,6.50,...,14,114.85,138,1132.08,16,131.26,2,16.41,41.02,1394.59
1,Marpletownship,PA,45,47616,1,23123,2.82,0.80,95.57,3.44,...,57,242.37,376,1598.78,26,110.55,1,4.25,127.56,1955.95
2,Tigardcity,OR,NaN,NaN,1,29344,2.43,0.74,94.33,3.43,...,274,758.14,1797,4972.19,136,376.3,22,60.87,218.59,6167.51
3,Gloversvillecity,NY,35,29443,1,16656,2.40,1.70,97.35,0.50,...,225,1301.78,716,4142.56,47,271.93,NaN,NaN,306.64,NaN
4,Bemidjicity,MN,7,5068,1,11245,2.76,0.53,89.16,1.17,...,91,728.93,1060,8490.87,91,728.93,5,40.05,NaN,9988.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2210,Mercedcity,CA,NaN,NaN,10,56216,3.07,6.87,61.68,15.23,...,1376,2268.72,2563,4225.82,489,806.25,34,56.06,545.75,7356.84
2211,Pinevillecity,LA,NaN,NaN,10,12251,2.68,21.18,76.65,1.52,...,104,860.43,574,4748.9,24,198.56,2,16.55,124.1,5824.44
2212,Yucaipacity,CA,NaN,NaN,10,32824,2.46,0.52,92.62,0.98,...,628,1709.26,895,2435.97,179,487.19,8,21.77,353.83,4654.2
2213,Beevillecity,TX,NaN,NaN,10,13547,2.89,3.37,69.91,0.90,...,192,1508.01,474,3722.9,13,102.1,1,7.85,691.17,5340.87
2214,WestSacramentocity,CA,NaN,NaN,10,28898,2.61,2.39,71.27,9.09,...,791,2614.53,1458,4819.2,405,1338.67,20,66.11,918.89,8838.5

In [6]:
list = data.replace('?', np.nan).isna().sum()

In [7]:
for elem in list:
    print(elem)

0
0
1221
1224
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1872
1872
1872
1872
1872
1872
1872
1872
1872
1872
1872
1872
1872
1872
1872
1872
1872
0
0
0
1872
1872
1872
1872
0
1872
0
0
208
208
1
1
13
13
3
3
3
3
3
3
91
91
221
97

In [8]:
data.columns

Index(['communityname', 'state', 'countyCode', 'communityCode', 'fold',
       'population', 'householdsize', 'racepctblack', 'racePctWhite',
       'racePctAsian',
       ...
       'burglaries', 'burglPerPop', 'larcenies', 'larcPerPop', 'autoTheft',
       'autoTheftPerPop', 'arsons', 'arsonsPerPop', 'ViolentCrimesPerPop',
       'nonViolPerPop'],
      dtype='object', length=147)

In [9]:
values = np.squeeze(np.asarray(list))

In [10]:
cols = np.squeeze(np.asarray(data.columns))

In [11]:
dictionary = dict(zip(cols.tolist(), values.tolist()))

In [12]:
dictionary

{'communityname': 0,
 'state': 0,
 'countyCode': 1221,
 'communityCode': 1224,
 'fold': 0,
 'population': 0,
 'householdsize': 0,
 'racepctblack': 0,
 'racePctWhite': 0,
 'racePctAsian': 0,
 'racePctHisp': 0,
 'agePct12t21': 0,
 'agePct12t29': 0,
 'agePct16t24': 0,
 'agePct65up': 0,
 'numbUrban': 0,
 'pctUrban': 0,
 'medIncome': 0,
 'pctWWage': 0,
 'pctWFarmSelf': 0,
 'pctWInvInc': 0,
 'pctWSocSec': 0,
 'pctWPubAsst': 0,
 'pctWRetire': 0,
 'medFamInc': 0,
 'perCapInc': 0,
 'whitePerCap': 0,
 'blackPerCap': 0,
 'indianPerCap': 0,
 'AsianPerCap': 0,
 'OtherPerCap': 1,
 'HispPerCap': 0,
 'NumUnderPov': 0,
 'PctPopUnderPov': 0,
 'PctLess9thGrade': 0,
 'PctNotHSGrad': 0,
 'PctBSorMore': 0,
 'PctUnemployed': 0,
 'PctEmploy': 0,
 'PctEmplManu': 0,
 'PctEmplProfServ': 0,
 'PctOccupManu': 0,
 'PctOccupMgmtProf': 0,
 'MalePctDivorce': 0,
 'MalePctNevMarr': 0,
 'FemalePctDiv': 0,
 'TotalPctDiv': 0,
 'PersPerFam': 0,
 'PctFam2Par': 0,
 'PctKids2Par': 0,
 'PctYoungKids2Par': 0,
 'PctTeen2Par': 0,
 'PctWorkMomYoungKids': 0,
 'PctWorkMom': 0,
 'NumKidsBornNeverMar': 0,
 'PctKidsBornNeverMar': 0,
 'NumImmig': 0,
 'PctImmigRecent': 0,
 'PctImmigRec5': 0,
 'PctImmigRec8': 0,
 'PctImmigRec10': 0,
 'PctRecentImmig': 0,
 'PctRecImmig5': 0,
 'PctRecImmig8': 0,
 'PctRecImmig10': 0,
 'PctSpeakEnglOnly': 0,
 'PctNotSpeakEnglWell': 0,
 'PctLargHouseFam': 0,
 'PctLargHouseOccup': 0,
 'PersPerOccupHous': 0,
 'PersPerOwnOccHous': 0,
 'PersPerRentOccHous': 0,
 'PctPersOwnOccup': 0,
 'PctPersDenseHous': 0,
 'PctHousLess3BR': 0,
 'MedNumBR': 0,
 'HousVacant': 0,
 'PctHousOccup': 0,
 'PctHousOwnOcc': 0,
 'PctVacantBoarded': 0,
 'PctVacMore6Mos': 0,
 'MedYrHousBuilt': 0,
 'PctHousNoPhone': 0,
 'PctWOFullPlumb': 0,
 'OwnOccLowQuart': 0,
 'OwnOccMedVal': 0,
 'OwnOccHiQuart': 0,
 'OwnOccQrange': 0,
 'RentLowQ': 0,
 'RentMedian': 0,
 'RentHighQ': 0,
 'RentQrange': 0,
 'MedRent': 0,
 'MedRentPctHousInc': 0,
 'MedOwnCostPctInc': 0,
 'MedOwnCostPctIncNoMtg': 0,
 'NumInShelters': 0,
 'NumStreet': 0,
 'PctForeignBorn': 0,
 'PctBornSameState': 0,
 'PctSameHouse85': 0,
 'PctSameCity85': 0,
 'PctSameState85': 0,
 'LemasSwornFT': 1872,
 'LemasSwFTPerPop': 1872,
 'LemasSwFTFieldOps': 1872,
 'LemasSwFTFieldPerPop': 1872,
 'LemasTotalReq': 1872,
 'LemasTotReqPerPop': 1872,
 'PolicReqPerOffic': 1872,
 'PolicPerPop': 1872,
 'RacialMatchCommPol': 1872,
 'PctPolicWhite': 1872,
 'PctPolicBlack': 1872,
 'PctPolicHisp': 1872,
 'PctPolicAsian': 1872,
 'PctPolicMinor': 1872,
 'OfficAssgnDrugUnits': 1872,
 'NumKindsDrugsSeiz': 1872,
 'PolicAveOTWorked': 1872,
 'LandArea': 0,
 'PopDens': 0,
 'PctUsePubTrans': 0,
 'PolicCars': 1872,
 'PolicOperBudg': 1872,
 'LemasPctPolicOnPatr': 1872,
 'LemasGangUnitDeploy': 1872,
 'LemasPctOfficDrugUn': 0,
 'PolicBudgPerPop': 1872,
 'murders': 0,
 'murdPerPop': 0,
 'rapes': 208,
 'rapesPerPop': 208,
 'robberies': 1,
 'robbbPerPop': 1,
 'assaults': 13,
 'assaultPerPop': 13,
 'burglaries': 3,
 'burglPerPop': 3,
 'larcenies': 3,
 'larcPerPop': 3,
 'autoTheft': 3,
 'autoTheftPerPop': 3,
 'arsons': 91,
 'arsonsPerPop': 91,
 'ViolentCrimesPerPop': 221,
 'nonViolPerPop': 97}

In [13]:
data.RentMedian.describe()

count    2215.000000
mean      428.537246
std       170.706644
min       120.000000
25%       289.500000
50%       397.000000
75%       544.000000
max      1001.000000
Name: RentMedian, dtype: float64

In [14]:
data.describe()

,fold,population,householdsize,racepctblack,racePctWhite,racePctAsian,racePctHisp,agePct12t21,agePct12t29,agePct16t24,...,PctBornSameState,PctSameHouse85,PctSameCity85,PctSameState85,LandArea,PopDens,PctUsePubTrans,LemasPctOfficDrugUn,murders,murdPerPop
count,2215.000000,2.215000e+03,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,...,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000
mean,5.494357,5.311798e+04,2.707327,9.335102,83.979819,2.670203,7.950176,14.445837,27.644840,13.975142,...,61.539630,51.538596,77.411079,88.111865,27.419955,2783.835034,3.041124,0.980163,7.764786,5.859296
std,2.872924,2.046203e+05,0.334120,14.247156,16.419080,4.473843,14.589832,4.518623,6.181517,5.970747,...,16.750061,10.517926,10.878186,7.287836,109.822600,2828.993341,4.912917,2.877128,58.166468,9.156829
min,1.000000,1.000500e+04,1.600000,0.000000,2.680000,0.030000,0.120000,4.580000,9.380000,4.640000,...,6.750000,11.830000,27.950000,32.830000,0.900000,10.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,1.436600e+04,2.500000,0.860000,76.320000,0.620000,0.930000,12.250000,24.415000,11.320000,...,50.110000,44.995000,72.060000,85.200000,7.300000,1181.900000,0.360000,0.000000,0.000000,0.000000
50%,5.000000,2.279200e+04,2.660000,2.870000,90.350000,1.230000,2.180000,13.620000,26.780000,12.540000,...,64.490000,52.170000,79.490000,90.030000,13.700000,2027.300000,1.220000,0.000000,1.000000,2.170000
75%,8.000000,4.302400e+04,2.850000,11.145000,96.225000,2.670000,7.810000,15.360000,29.205000,14.345000,...,74.855000,58.740000,85.135000,93.010000,26.100000,3321.700000,3.365000,0.000000,3.000000,8.365000
max,10.000000,7.322564e+06,5.280000,96.670000,99.630000,57.460000,95.290000,54.400000,70.510000,63.620000,...,93.140000,78.560000,96.590000,99.900000,3569.800000,44229.900000,54.330000,48.440000,1946.000000,91.090000

In [15]:
data.describe().iat[1,1] # first '1' is a row index (mean), second index is a column index

53117.9841986456

In [16]:
data1 = data.replace('?', np.nan)
data1

,communityname,state,countyCode,communityCode,fold,population,householdsize,racepctblack,racePctWhite,racePctAsian,...,burglaries,burglPerPop,larcenies,larcPerPop,autoTheft,autoTheftPerPop,arsons,arsonsPerPop,ViolentCrimesPerPop,nonViolPerPop
0,BerkeleyHeightstownship,NJ,39,5320,1,11980,3.10,1.37,91.78,6.50,...,14,114.85,138,1132.08,16,131.26,2,16.41,41.02,1394.59
1,Marpletownship,PA,45,47616,1,23123,2.82,0.80,95.57,3.44,...,57,242.37,376,1598.78,26,110.55,1,4.25,127.56,1955.95
2,Tigardcity,OR,NaN,NaN,1,29344,2.43,0.74,94.33,3.43,...,274,758.14,1797,4972.19,136,376.3,22,60.87,218.59,6167.51
3,Gloversvillecity,NY,35,29443,1,16656,2.40,1.70,97.35,0.50,...,225,1301.78,716,4142.56,47,271.93,NaN,NaN,306.64,NaN
4,Bemidjicity,MN,7,5068,1,11245,2.76,0.53,89.16,1.17,...,91,728.93,1060,8490.87,91,728.93,5,40.05,NaN,9988.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2210,Mercedcity,CA,NaN,NaN,10,56216,3.07,6.87,61.68,15.23,...,1376,2268.72,2563,4225.82,489,806.25,34,56.06,545.75,7356.84
2211,Pinevillecity,LA,NaN,NaN,10,12251,2.68,21.18,76.65,1.52,...,104,860.43,574,4748.9,24,198.56,2,16.55,124.1,5824.44
2212,Yucaipacity,CA,NaN,NaN,10,32824,2.46,0.52,92.62,0.98,...,628,1709.26,895,2435.97,179,487.19,8,21.77,353.83,4654.2
2213,Beevillecity,TX,NaN,NaN,10,13547,2.89,3.37,69.91,0.90,...,192,1508.01,474,3722.9,13,102.1,1,7.85,691.17,5340.87
2214,WestSacramentocity,CA,NaN,NaN,10,28898,2.61,2.39,71.27,9.09,...,791,2614.53,1458,4819.2,405,1338.67,20,66.11,918.89,8838.5

In [17]:
# 6. dokonać imputacji braków, wybraną metodą, dla przynajmniej 3 różnych zmiennych

In [18]:
# check how many zeroes per column and not more than 20 missing values
imp_columns = []

for i in range (len(data.isna().sum())):
    
    if data1.isna().sum()[i] != 0 and data1.isna().sum()[i] < 20:
        
        imp_columns.append(data1.isna().sum().index[i]) # will use it later
        
        print(data1.isna().sum().index[i], data1.isna().sum()[i])

OtherPerCap 1
robberies 1
robbbPerPop 1
assaults 13
assaultPerPop 13
burglaries 3
burglPerPop 3
larcenies 3
larcPerPop 3
autoTheft 3
autoTheftPerPop 3

In [19]:
# rows with values to be replaced
data1[data1['burglaries'].isnull()]

,communityname,state,countyCode,communityCode,fold,population,householdsize,racepctblack,racePctWhite,racePctAsian,...,burglaries,burglPerPop,larcenies,larcPerPop,autoTheft,autoTheftPerPop,arsons,arsonsPerPop,ViolentCrimesPerPop,nonViolPerPop
61,Mesquitecity,TX,NaN,NaN,1,101484,2.83,5.83,87.21,2.63,...,NaN,NaN,5181,4475.25,761,657.34,93,80.33,566.64,NaN
1700,Lamesacity,TX,NaN,NaN,8,10809,2.82,5.39,67.49,0.16,...,NaN,NaN,NaN,NaN,4,37.17,0,0,706.19,NaN
1878,BayCitycity,TX,NaN,NaN,9,18170,2.73,17.51,66.29,1.43,...,NaN,NaN,1379,7165.5,65,337.75,3,15.59,592.36,NaN

In [20]:
# replacing missing values with mean values
#for col in imp_columns:
    
 #   for row in data[data[col]== 0].index:
        
  #      data[col][row] = data.describe()[col][1]

In [21]:
# replacing missing values with mean values
data1.autoTheft = data1.autoTheft.astype('float')
data1['autoTheft'][1426] = data1.describe().autoTheft[1]
data1['autoTheft'][1609] = data1.describe().autoTheft[1]
data1['autoTheft'][1782] = data1.describe().autoTheft[1]

data1.larcenies = data1.larcenies.astype('float')

data1['larcenies'][436] = data1.describe().larcenies[1]
data1['larcenies'][1426] = data1.describe().larcenies[1]
data1['larcenies'][1700] = data1.describe().larcenies[1]

data1.burglaries = data1.burglaries.astype('float')

data1['burglaries'][61] = data1.describe().burglaries[1]
data1['burglaries'][1700] = data1.describe().burglaries[1]
data1['burglaries'][1878] = data1.describe().burglaries[1]

/Users/macbook/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/macbook/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Users/macbook/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/macbook/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/Users/macbook/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/Users/macbook/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/Users/macbook/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/Users/macbook/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
/Users/macbook/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
data1.burglaries

0         14.0
1         57.0
2        274.0
3        225.0
4         91.0
         ...
2210    1376.0
2211     104.0
2212     628.0
2213     192.0
2214     791.0
Name: burglaries, Length: 2215, dtype: float64

In [23]:
# dokonać normalizacji zbioru danych przynajmniej 4 wybranymi metodami,  
# przedstawić wybrane metody, 
# uzasadnić wybór metody, 
# do dalszej analizy wybrać jeden wariant, 

from sklearn import preprocessing

In [121]:
# 1. Normalizacja min-max
# Ta metoda przeprowadza liniową transformację pierwotnych danych najczęściej do przedziału [0,1] według wzoru:
# przykład: 

#a = np.random.random((1, 4))
#a = a*20
a = [[23123,  56216, 16656, 32824  ]]
#print("Data = ", a)
type(a)

list

In [117]:
normalized = preprocessing.normalize(a)
print("Normalized Data = ", normalized)

Normalized Data =  [[0.3253938  0.79108844 0.23438824 0.46190919]]

In [96]:
# Wybór kolumn do normalizacji

data1.columns.to_series().groupby(data1.dtypes).groups

{dtype('int64'): Index(['fold', 'population', 'numbUrban', 'medIncome', 'medFamInc',
        'perCapInc', 'whitePerCap', 'blackPerCap', 'indianPerCap',
        'AsianPerCap', 'HispPerCap', 'NumUnderPov', 'NumKidsBornNeverMar',
        'NumImmig', 'MedNumBR', 'HousVacant', 'MedYrHousBuilt',
        'OwnOccLowQuart', 'OwnOccMedVal', 'OwnOccHiQuart', 'OwnOccQrange',
        'RentLowQ', 'RentMedian', 'RentHighQ', 'RentQrange', 'MedRent',
        'NumInShelters', 'NumStreet', 'murders'],
       dtype='object'),
 dtype('float64'): Index(['householdsize', 'racepctblack', 'racePctWhite', 'racePctAsian',
        'racePctHisp', 'agePct12t21', 'agePct12t29', 'agePct16t24',
        'agePct65up', 'pctUrban', 'pctWWage', 'pctWFarmSelf', 'pctWInvInc',
        'pctWSocSec', 'pctWPubAsst', 'pctWRetire', 'PctPopUnderPov',
        'PctLess9thGrade', 'PctNotHSGrad', 'PctBSorMore', 'PctUnemployed',
        'PctEmploy', 'PctEmplManu', 'PctEmplProfServ', 'PctOccupManu',
        'PctOccupMgmtProf', 'MalePctDivorce', 'MalePctNevMarr', 'FemalePctDiv',
        'TotalPctDiv', 'PersPerFam', 'PctFam2Par', 'PctKids2Par',
        'PctYoungKids2Par', 'PctTeen2Par', 'PctWorkMomYoungKids', 'PctWorkMom',
        'PctKidsBornNeverMar', 'PctImmigRecent', 'PctImmigRec5', 'PctImmigRec8',
        'PctImmigRec10', 'PctRecentImmig', 'PctRecImmig5', 'PctRecImmig8',
        'PctRecImmig10', 'PctSpeakEnglOnly', 'PctNotSpeakEnglWell',
        'PctLargHouseFam', 'PctLargHouseOccup', 'PersPerOccupHous',
        'PersPerOwnOccHous', 'PersPerRentOccHous', 'PctPersOwnOccup',
        'PctPersDenseHous', 'PctHousLess3BR', 'PctHousOccup', 'PctHousOwnOcc',
        'PctVacantBoarded', 'PctVacMore6Mos', 'PctHousNoPhone',
        'PctWOFullPlumb', 'MedRentPctHousInc', 'MedOwnCostPctInc',
        'MedOwnCostPctIncNoMtg', 'PctForeignBorn', 'PctBornSameState',
        'PctSameHouse85', 'PctSameCity85', 'PctSameState85', 'LandArea',
        'PopDens', 'PctUsePubTrans', 'LemasPctOfficDrugUn', 'murdPerPop',
        'burglaries', 'larcenies', 'autoTheft'],
       dtype='object'),
 dtype('O'): Index(['communityname', 'state', 'countyCode', 'communityCode', 'OtherPerCap',
        'LemasSwornFT', 'LemasSwFTPerPop', 'LemasSwFTFieldOps',
        'LemasSwFTFieldPerPop', 'LemasTotalReq', 'LemasTotReqPerPop',
        'PolicReqPerOffic', 'PolicPerPop', 'RacialMatchCommPol',
        'PctPolicWhite', 'PctPolicBlack', 'PctPolicHisp', 'PctPolicAsian',
        'PctPolicMinor', 'OfficAssgnDrugUnits', 'NumKindsDrugsSeiz',
        'PolicAveOTWorked', 'PolicCars', 'PolicOperBudg', 'LemasPctPolicOnPatr',
        'LemasGangUnitDeploy', 'PolicBudgPerPop', 'rapes', 'rapesPerPop',
        'robberies', 'robbbPerPop', 'assaults', 'assaultPerPop', 'burglPerPop',
        'larcPerPop', 'autoTheftPerPop', 'arsons', 'arsonsPerPop',
        'ViolentCrimesPerPop', 'nonViolPerPop'],
       dtype='object')}

In [92]:
for col in data1.columns:
    if data1[col].dtype == 'int64' or data1[col].dtype == 'float64':
        print(col, data1[col].dtype)

fold int64
population int64
householdsize float64
racepctblack float64
racePctWhite float64
racePctAsian float64
racePctHisp float64
agePct12t21 float64
agePct12t29 float64
agePct16t24 float64
agePct65up float64
numbUrban int64
pctUrban float64
medIncome int64
pctWWage float64
pctWFarmSelf float64
pctWInvInc float64
pctWSocSec float64
pctWPubAsst float64
pctWRetire float64
medFamInc int64
perCapInc int64
whitePerCap int64
blackPerCap int64
indianPerCap int64
AsianPerCap int64
HispPerCap int64
NumUnderPov int64
PctPopUnderPov float64
PctLess9thGrade float64
PctNotHSGrad float64
PctBSorMore float64
PctUnemployed float64
PctEmploy float64
PctEmplManu float64
PctEmplProfServ float64
PctOccupManu float64
PctOccupMgmtProf float64
MalePctDivorce float64
MalePctNevMarr float64
FemalePctDiv float64
TotalPctDiv float64
PersPerFam float64
PctFam2Par float64
PctKids2Par float64
PctYoungKids2Par float64
PctTeen2Par float64
PctWorkMomYoungKids float64
PctWorkMom float64
NumKidsBornNeverMar int64
PctKidsBornNeverMar float64
NumImmig int64
PctImmigRecent float64
PctImmigRec5 float64
PctImmigRec8 float64
PctImmigRec10 float64
PctRecentImmig float64
PctRecImmig5 float64
PctRecImmig8 float64
PctRecImmig10 float64
PctSpeakEnglOnly float64
PctNotSpeakEnglWell float64
PctLargHouseFam float64
PctLargHouseOccup float64
PersPerOccupHous float64
PersPerOwnOccHous float64
PersPerRentOccHous float64
PctPersOwnOccup float64
PctPersDenseHous float64
PctHousLess3BR float64
MedNumBR int64
HousVacant int64
PctHousOccup float64
PctHousOwnOcc float64
PctVacantBoarded float64
PctVacMore6Mos float64
MedYrHousBuilt int64
PctHousNoPhone float64
PctWOFullPlumb float64
OwnOccLowQuart int64
OwnOccMedVal int64
OwnOccHiQuart int64
OwnOccQrange int64
RentLowQ int64
RentMedian int64
RentHighQ int64
RentQrange int64
MedRent int64
MedRentPctHousInc float64
MedOwnCostPctInc float64
MedOwnCostPctIncNoMtg float64
NumInShelters int64
NumStreet int64
PctForeignBorn float64
PctBornSameState float64
PctSameHouse85 float64
PctSameCity85 float64
PctSameState85 float64
LandArea float64
PopDens float64
PctUsePubTrans float64
LemasPctOfficDrugUn float64
murders int64
murdPerPop float64
burglaries float64
larcenies float64
autoTheft float64

In [130]:
pop = data1.population.to_numpy()
pop

array([11980, 23123, 29344, ..., 32824, 13547, 28898])

In [136]:
pop1 = pop.reshape(1,-1)

In [142]:
pop2 = pop1.tolist()

In [143]:
normalized_population = preprocessing.normalize(pop2)

In [144]:
normalized_population

array([[0.00120435, 0.00232455, 0.00294995, ..., 0.00329979, 0.00136188,
        0.00290511]])

In [145]:
# 2. Normalizacja Z-score (lub Zero-Mean).
#
#

In [ ]:
# 3. Normalizacja poprzez skalowanie decymalne.
# Ta metoda normalizuje przesuwając przecinek w liczbach dziesiętnych. Ten typ skalowania przekształca dane do przedziału [-1,1] według wzoru